name: 'Push aar to bv-libs'
description: '推送aar到bv-libs仓库的可重用action'
inputs:
  SOURCE_AAR:
    description: '源aar文件的完整路径'
    required: true
    type: string
  TARGET_NAME:
    description: '目标库名称'
    required: true
    type: string
  TARGET_DIR:
    description: '目标仓库中的目录'
    required: true
    type: string
  TARGET_AAR:
    description: '目标aar文件名'
    required: true
    type: string
  BUILD_DATE:
    description: '构建日期'
    required: true
    type: string
  TARGET_REPO:
    description: '目标仓库ssh地址'
    required: false
    type: string
    default: 'git@github.com:zxgv5/bv-libs.git'
  BV_LIBS_DEPLOY_KEY:  # 关键修正：将密钥改为input参数
    description: '推送bv-libs的ssh私钥'
    required: true
    type: string

runs:
  using: 'composite'
  steps:
    - name: Push aar to bv-libs repository
      env:
        TARGET_REPO: ${{ inputs.TARGET_REPO }}
        SOURCE_AAR: ${{ inputs.SOURCE_AAR }}
        TARGET_NAME: ${{ inputs.TARGET_NAME }}
        TARGET_DIR: ${{ inputs.TARGET_DIR }}
        TARGET_AAR: ${{ inputs.TARGET_AAR }}
        BUILD_DATE: ${{ inputs.BUILD_DATE }}
        BV_LIBS_DEPLOY_KEY: ${{ inputs.BV_LIBS_DEPLOY_KEY }}  # 读取input传入的密钥
      run: |
        # 设置 ssh 密钥和配置
        echo "Setting up ssh configuration..."
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        # 写入私钥
        echo "${BV_LIBS_DEPLOY_KEY}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        # 配置 ssh 不验证主机
        echo "Host github.com" >> ~/.ssh/config
        echo "  StrictHostKeyChecking no" >> ~/.ssh/config
        echo "  UserKnownHostsFile /dev/null" >> ~/.ssh/config
        chmod 600 ~/.ssh/config
        # 测试 ssh 连接
        echo "Testing ssh connection to GitHub..."
        ssh -T git@github.com 2>&1 | grep -v "successfully authenticated" || true
        # 设置 Git 配置
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git config --global init.defaultBranch main
        # 克隆目标仓库
        cd "$GITHUB_WORKSPACE"
        echo "Cloning target repository: $TARGET_REPO"
        git clone $TARGET_REPO target-repo
        cd target-repo
        # 确保在 main 分支
        git checkout main
        # 检查 aar 文件是否存在
        if [ -f "$SOURCE_AAR" ]; then
          echo "✓ Found aar file: $SOURCE_AAR"
          # 确保目标目录存在
          mkdir -p "$TARGET_DIR"
          # 复制新文件
          echo "Copying new aar file..."
          cp -v "$SOURCE_AAR" "$TARGET_DIR/$TARGET_AAR"
          # 提交更改
          echo "Committing changes..."
          git add "$TARGET_DIR/$TARGET_AAR"
          # 检查是否有更改
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update $TARGET_NAME aar - $BUILD_DATE [CI]"
            echo "Pushing to remote repository..."
            git push origin main
            echo "✓ Successfully pushed $TARGET_NAME aar to $TARGET_REPO"
          fi
        else
          echo "✗ Error: aar file not found at $SOURCE_AAR"
          exit 1
        fi
        # 清理 ssh 密钥
        rm -f ~/.ssh/id_ed25519
        rm -f ~/.ssh/config
      shell: bash